default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test-api_development

test:
  <<: *default
  database: test-api_test

production:
  <<: *default
  database: test-api_production
  username: test-api
  password: <%= ENV['TEST_API_DATABASE_PASSWORD'] %>
